version: 2
updates:
    - package-ecosystem: 'gomod'
      directory: '/'
      schedule:
          interval: 'daily'
          time: '17:00'
          timezone: 'Africa/Johannesburg'
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "daily"
        time: "17:00"
        timezone: "Africa/Johannesburg"
        