# Air configuration for vortludo
# Reference: https://github.com/air-verse/air


[build]
  # Windows-compatible build command
  cmd = "cls && go build -o tmp/main.exe ."
  bin = "tmp/main.exe"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["static", "templates", "data"]
  exclude_file = ["*_test.go"]
  delay = 1000

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[log]
  time = true

[debug]
  enable = false
