services:
  - type: web
    name: vortludo
    env: go
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app
    startCommand: ./app
    envVars:
      - key: GIN_MODE
        value: release
      - key: ENV
        value: production
      - key: PORT
        value: 10000
