services:
    - type: web
      name: vortludo
      runtime: go
      buildCommand: go build -tags netgo -ldflags '-s -w' -o vortludo
      startCommand: ./vortludo
      envVars:
          - key: GIN_MODE
            value: release
          - key: ENV
            value: production
          - key: PORT
            value: 10000
          - key: SESSION_TIMEOUT
            value: 1h
          - key: COOKIE_MAX_AGE
            value: 1h
          - key: STATIC_CACHE_AGE
            value: 5m
          - key: RATE_LIMIT_RPS
            value: 5
          - key: RATE_LIMIT_BURST
            value: 10
