name: Go

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.25'

            - name: Install dependencies
              run: go mod tidy && go mod download
              working-directory: ${{ github.workspace }}

            - name: Create required directories
              run: mkdir -p data
              working-directory: ${{ github.workspace }}

            - name: Build application
              run: go build -v ./...
              working-directory: ${{ github.workspace }}

            - name: Test
              run: go test -v ./...
              working-directory: ${{ github.workspace }}

            - name: Build production binary
              run: go build -tags netgo -ldflags '-s -w' -o vortludo ./cmd/vortludo
